import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

// Generated by scripts/sync_content.py from docs/. Do not edit
// src/content/replication/*.md by hand; re-run the script instead.
const replication = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/replication" }),
  schema: z.object({
    title: z.string(),
    blurb: z.string(),
    order: z.number(),
  }),
});

// Generated by scripts/sync_guide.py from the exuber vignettes. Do not edit by hand.
const guide = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/guide" }),
  schema: z.object({
    title: z.string(),
    blurb: z.string(),
    group: z.string(),
    order: z.number(),
    family: z.string().optional(),
  }),
});

export const collections = { replication, guide };
