import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

// Generated by scripts/sync-content.R from docs/enhancements/ — do not edit
// src/content/replication/*.md by hand, re-run the script instead.
const replication = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/replication" }),
  schema: z.object({
    title: z.string(),
    blurb: z.string(),
    order: z.number(),
  }),
});

export const collections = { replication };
